language: python
dist: xenial
python:
  - "3.5"
addons:
  chrome: stable
install:
  - pip install -r requirements.txt
  - python wordwrench/manage.py migrate
  - mkdir bin
  - wget -P bin https://chromedriver.storage.googleapis.com/75.0.3770.8/chromedriver_linux64.zip
  - unzip bin/chromedriver_linux64.zip -d bin
  - rm bin/chromedriver_linux64.zip
  - chmod +x bin/chromedriver
  - PATH=$PWD/bin:$PATH
  - npm install
script:
  - cd wordwrench
  - python manage.py test
  - python manage.py test functional_tests
  - npm run test
  - python manage.py collectstatic --noinput
  - cd ..
  - coverage run --source=. --omit=wordwrench/manage.py wordwrench/manage.py test --noinput
after_success:
  - coveralls
